### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by supperfreddo** [FujiwaraChoki/MoneyPrinterV2#10]
Error:
```
Traceback (most recent call last):
  File "C:\Users\Fred\Documents\GitHub\MoneyPrinterV2\src\main.py", line 363, in <module>
    main()
  File "C:\Users\Fred\Documents\GitHub\MoneyPrinterV2\src\main.py", line 113, in main
    for video in videos:
TypeError: 'NoneType' object is not iterable
```
Got error whilst using option '2. Show all Shorts':
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/9703184/e5713022-bdc8-4923-a952-b5db9665dced)

**Comment by FujiwaraChoki** [comment]
Where is the error in the screenshot?

**Comment by FujiwaraChoki** [comment]
Also, that just means you haven't yet uploaded any videos through MPV2. MPV2 doesn't dynamically fetch your previously uploaded Shorts, but gets them from the `youtube.json` cache file.

**Comment by supperfreddo** [comment]
The caching functionality seems to be unfinished. I have made a PR for it.
#14
