### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by supperfreddo** [FujiwaraChoki/MoneyPrinterV2#11]
Error:
```
Traceback (most recent call last):
  File "C:\Users\Fred\Documents\GitHub\MoneyPrinterV2\src\main.py", line 362, in <module>
    main()
  File "C:\Users\Fred\Documents\GitHub\MoneyPrinterV2\src\main.py", line 112, in main
    for video in videos:
TypeError: 'NoneType' object is not iterable
```
Got error whilst using option '2. Show all Shorts':
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/9703184/33f824bc-5ff1-4ecc-8b20-b1433864fa9b)
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/9703184/ab342f1f-1126-42de-a362-579cf5545f46)

Error gets thrown at line 112 in main.py because videos variable is not iterable. Variable videos is 'None' instead.

**Comment by FujiwaraChoki** [comment]
I answered your question in a previous issue. Stop opening new ones please.
