### ISSUE TITLE
can not download song zip file

### ISSUE THREAD

**Issue by alanzou** [FujiwaraChoki/MoneyPrinterV2#12]
https://filebin.net/klylrens0uk2pnrg/drive-download-20240209T180019Z-001.zip

The file has been requested too many times.

**Comment by FujiwaraChoki** [comment]
Yes, please join the discord and check the pinned message in the help channel. You will find the file there.

**Comment by haru-mamburu** [comment]
Thanks for your work, @FujiwaraChoki! Could you provide the link to join the Discord?

**Comment by FujiwaraChoki** [comment]
> Thanks for your work, @FujiwaraChoki! Could you provide the link to join the Discord?

https://dsc.gg/fuji-community

**Comment by fxgurv** [comment]
![image](https://github.com/user-attachments/assets/c2593fc3-3206-4477-8d1a-4749eef6617d)

**Comment by fxgurv** [comment]
![image](https://github.com/user-attachments/assets/f5ab76e7-9a8a-4161-aff2-163935b7f2b2)

**Comment by fxgurv** [comment]
![image](https://github.com/user-attachments/assets/2ade4aeb-f577-496f-88fd-9f9985ca9152)

**Comment by FujiwaraChoki** [comment]
Hey everybody,

Unfortunately I do not have the songs stored in my PC anymore, as I got myself a new one.

**Comment by FujiwaraChoki** [comment]
> ![image](https://private-user-images.githubusercontent.com/168190107/391238332-2ade4aeb-f577-496f-88fd-9f9985ca9152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNDg4NDQsIm5iZiI6MTczMzA0ODU0NCwicGF0aCI6Ii8xNjgxOTAxMDcvMzkxMjM4MzMyLTJhZGU0YWViLWY1NzctNDk2Zi04OGZkLTlmOTk4NWNhOTE1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMDIyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTA4OGIxYzY0ZjNmN2JkMmRjM2RmZjk4NmZhNTU1MjM4MDAyNGVhYThmNjUwYTJlOTcwN2QzYmIyMmE1ZjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OqHvJ9AtnUYUcle35gDy_IRn52zvwXErZwdrZ0XRwKo)

You were probably banned or something, the invite links works for me, I tested it.

**Comment by RanKey1496** [comment]
https://filebin.net/0wcu483v7xv5ss5y/songs.zip

Thats my songs.zip, feel free to download is not copyrighted

**Comment by idk73248** [comment]
> https://filebin.net/0wcu483v7xv5ss5y/songs.zip
> 
> Thats my songs.zip, feel free to download is not copyrighted

it says its no longer available

**Comment by FujiwaraChoki** [comment]
> > https://filebin.net/0wcu483v7xv5ss5y/songs.zip
> > 
> > Thats my songs.zip, feel free to download is not copyrighted
> 
> it says its no longer available

You can curate your own list, it's pretty easy!

1. Download a bunch of songs you like
2. Zip them all into a file called songs.zip
3. Upload the file to filebin.io
4. Copy the link to the Zip file. You can hover over the download button, and that's the link you need.
