### ISSUE TITLE
Selenium Failed

### ISSUE THREAD

**Issue by dwoloszin** [FujiwaraChoki/MoneyPrinterV2#17]
Hi, how to solve this error:

![fail1](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/10993738/643b5faf-a1f1-434e-9047-8dfedccd2fec)

**Comment by FujiwaraChoki** [comment]
Wrong Firefox Profile Path.

**Comment by dwoloszin** [comment]
> Wrong Firefox Profile Path.

How to fix? Do you have a valid path to show?

**Comment by FujiwaraChoki** [comment]
No, it depends on your system completely, so it varies a lot. You should be able to find it by searching for tutorials on Google.
