### ISSUE TITLE
Youtube shorts generation: OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by omansh-arora** [FujiwaraChoki/MoneyPrinterV2#18]
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/100989540/b13c8b26-3e94-4265-a386-86872d913f29)

**Comment by omansh-arora** [comment]
Different error too:

![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/100989540/85b9ca30-0400-47c6-aa89-b32ae6dd1a5d)

**Comment by FujiwaraChoki** [comment]
Was this a one time thing or does this happen frequently?

**Comment by omansh-arora** [comment]
It happens after 1 short is created

**Comment by FujiwaraChoki** [comment]
It is probably a bug where MoviePy failed to close the file after creating it. I will have a look at it.

**Comment by InternalShadow** [comment]
having an issue while first running the script
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/76181682/1054e5ad-f402-4b95-8060-a9bb67037173)

**Comment by ElvisDream** [comment]
I had a similar problem, but I didn't generate a single short successfully
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/26276217/1637b592-3990-48fd-ad29-9906a68a03a6)

**Comment by FujiwaraChoki** [comment]
@ElvisDream Sorry I can't read chinese, but the issue here is that it was not able to use the `gpt4free` package correctly. I recommend using a VPN.

**Comment by FujiwaraChoki** [comment]
I just noticed that it applies to both 🤦

I will close this issue, as the solution is to use a VPN.

**Comment by ElvisDream** [comment]
But I use a VPN all the time

**Comment by YotomiY** [comment]
Got the error using a vpn all the time
