### ISSUE TITLE
FileNotFoundError   :     .models.json

### ISSUE THREAD

**Issue by MB14eth** [FujiwaraChoki/MoneyPrinterV2#26]
Hi, how can I fix this issue please, I'm stuck
<img width="1137" alt="Screenshot 2024-02-20 at 19 28 01" src="https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/107208305/7d0ae40d-301d-410f-a9ee-b6b8185ea6f9">

**Comment by kerta1n** [comment]
for reference,

https://discord.com/channels/1134848537704804432/1134885769383792650/1209877661992882196
