### ISSUE TITLE
MoviePy Failing To Read Songs.zip

### ISSUE THREAD

**Issue by OPTIC7409** [FujiwaraChoki/MoneyPrinterV2#27]
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/79322893/13e247f5-63e9-4f12-a641-cfc4836c836b)
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/79322893/fdc6c149-3070-43df-a523-24c73ffce879)

Occurs when trying to generate a short for the first time

**Comment by BreuerChristian** [comment]
You can find it in the discord community and here https://www.transfernow.net/de/bld?utm_source=20240218KGFOlzyH
