### ISSUE TITLE
firefox_profile

### ISSUE THREAD

**Issue by hpglw** [FujiwaraChoki/MoneyPrinterV2#28]
I don't understand what exactly firefox_profile refers to. Is it the personal account link of the Firefox browser? Or is it the profile folder in the installation directory of Firefox? Could you please provide more detailed explanation?

**Comment by FranklinOP-IND** [comment]
C:\\Users\\Pc\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\ENTERYOURPRFILENAME
EDIT ON youtube.json

**Comment by hpglw** [comment]
This is my config configuration：
`{
  "verbose": true,
  "firefox_profile": "C:\Users\chia-06\AppData\Local\Mozilla\Firefox\Profiles\06fyxeuj.default-release",
  "headless": false,
  "twitter_language": "English",
  "llm": "gpt4",
  "image_prompt_llm": "gpt35_turbo",
  "image_model": "prodia",
  "threads": 2,
  "zip_url": "",
  "is_for_kids": false,
  "google_maps_scraper": "https://github.com/gosom/google-maps-scraper/archive/refs/tags/v0.9.7.zip",
  "email": {
    "smtp_server": "smtp.gmail.com",
    "smtp_port": 587,
    "username": "",
    "password": ""
  },
  "google_maps_scraper_niche": "",
  "scraper_timeout": 300,
  "outreach_message_subject": "I have a question...",
  "outreach_message_body_file": "outreach_message.html",
  "assembly_ai_api_key": "",
  "font": "bold_font.ttf",
  "imagemagick_path": "Path to magick.exe or on linux/macOS just /usr/bin/convert"
}`
After running python main.py, the following error is displayed：
`Traceback (most recent call last):
  File "C:\Users\chia-06\MoneyPrinterV2\src\main.py", line 14, in <module>
    from classes.YouTube import YouTube
  File "C:\Users\chia-06\MoneyPrinterV2\src\classes\YouTube.py", line 30, in <module>
    change_settings({"IMAGEMAGICK_BINARY": get_imagemagick_path()})
  File "C:\Users\chia-06\MoneyPrinterV2\src\config.py", line 242, in get_imagemagick_path
    return json.load(file)["imagemagick_path"]
  File "C:\Users\chia-06\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\chia-06\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\chia-06\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\chia-06\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 25 (char 45)`

**Comment by FranklinOP-IND** [comment]
U set IMAGEMAGICK_BINARY Path ?

**Comment by hpglw** [comment]
Now there is a new error, and I find this tool seems to be very difficult to use：

Traceback (most recent call last):
  File "C:\Users\chia-06\MoneyPrinterV2\src\main.py", line 364, in <module>
    main()
  File "C:\Users\chia-06\MoneyPrinterV2\src\main.py", line 79, in main
    youtube = YouTube(
  File "C:\Users\chia-06\MoneyPrinterV2\src\classes\YouTube.py", line 80, in __init__
    self.service: Service = Service(GeckoDriverManager().install())
  File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\firefox.py", line 39, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path
    binary_path = self._cache_manager.find_driver(driver)
  File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\driver_cache.py", line 105, in find_driver
    driver_version = self.get_cache_key_driver_version(driver)
  File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\driver_cache.py", line 152, in get_cache_key_driver_version
    return driver.get_driver_version_to_download()
  File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
  File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\drivers\firefox.py", line 29, in get_latest_release_version
    resp = self._http_client.get(
  File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\http.py", line 36, in get
    self.validate_response(resp)
  File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\http.py", line 19, in validate_response
    raise ValueError(
ValueError: response body:
{"message":"API rate limit exceeded for 38.150.12.171. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

request url:
https://api.github.com/repos/mozilla/geckodriver/releases/latest
response headers:
{'Date': 'Wed, 21 Feb 2024 13:34:29 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1708524067', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '279', 'X-GitHub-Request-Id': '50D4:183308:151D5F:1665F5:65D5FBE4'}

**Comment by bartex100** [comment]
> Now there is a new error, and I find this tool seems to be very difficult to use：
> 
> Traceback (most recent call last):
>   File "C:\Users\chia-06\MoneyPrinterV2\src\main.py", line 364, in <module>
>     main()
>   File "C:\Users\chia-06\MoneyPrinterV2\src\main.py", line 79, in main
>     youtube = YouTube(
>   File "C:\Users\chia-06\MoneyPrinterV2\src\classes\YouTube.py", line 80, in __init__
>     self.service: Service = Service(GeckoDriverManager().install())
>   File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\firefox.py", line 39, in install
>     driver_path = self._get_driver_binary_path(self.driver)
>   File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path
>     binary_path = self._cache_manager.find_driver(driver)
>   File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\driver_cache.py", line 105, in find_driver
>     driver_version = self.get_cache_key_driver_version(driver)
>   File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\driver_cache.py", line 152, in get_cache_key_driver_version
>     return driver.get_driver_version_to_download()
>   File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
>     return self.get_latest_release_version()
>   File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\drivers\firefox.py", line 29, in get_latest_release_version
>     resp = self._http_client.get(
>   File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\http.py", line 36, in get
>     self.validate_response(resp)
>   File "C:\Users\chia-06\MoneyPrinterV2\venv\lib\site-packages\webdriver_manager\core\http.py", line 19, in validate_response
>     raise ValueError(
> ValueError: response body:
> {"message":"API rate limit exceeded for 38.150.12.171. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
> 
> request url:
> https://api.github.com/repos/mozilla/geckodriver/releases/latest
> response headers:
> {'Date': 'Wed, 21 Feb 2024 13:34:29 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1708524067', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '279', 'X-GitHub-Request-Id': '50D4:183308:151D5F:1665F5:65D5FBE4'}

Would recommend to delete your message, there is your IP in the message

**Comment by FujiwaraChoki** [comment]
Please open seperate issues for seperate problems, and always embed your error, or make a screenshot of it, so others can understand your problem better.
