### ISSUE TITLE
UnboundLocalError: local variable 'account' referenced before assignment

### ISSUE THREAD

**Issue by FedeGioz** [FujiwaraChoki/MoneyPrinterV2#3]
Error:
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/63424787/ccd15a5e-4b2c-4f08-9aa3-a3429af23d7c)

twitter.json file:
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/63424787/048cfbff-ff70-4b5f-b80b-6241f381b057)

**Comment by FujiwaraChoki** [comment]
Will check out later

**Comment by FujiwaraChoki** [comment]
I have implemented a fix for this issue, by re-searching for the account even in the case where there are existing products. Try pulling from main and trying again.

**Comment by FujiwaraChoki** [comment]
Has this issue been resolved?
