### ISSUE TITLE
python 3.9.13 Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by InternalShadow** [FujiwaraChoki/MoneyPrinterV2#30]
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/76181682/edc83726-7fca-4123-a200-0c3aa237f1d5)

**Comment by FujiwaraChoki** [comment]
Do NOT alter the configuration names, just the values...

It seems like you have something like this:

```json
{
   name: "myName"
}
```

when it should be like this:

```json
{
   "name": "myName"
}
```

**Comment by InternalShadow** [comment]
I think when i filed out the 
<code>
"email":
{"username":"something1",
"password":"something2"
},
</code>
 it was erroring
