### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: Failed to set preferences: unknown error

### ISSUE THREAD

**Issue by ElvisDream** [FujiwaraChoki/MoneyPrinterV2#32]
When I select option 1 and then select a user, this exception will be thrown after execution. Is it caused by the mismatch between the browser version and the driver? Which browser version is required? thank you.

python version:3.11.6
firfox version:123.0 (64 位)

> Traceback (most recent call last):
  File "D:\MyProject\PYTHON\MoneyPrinterV2-main\venv\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "D:\MyProject\PYTHON\MoneyPrinterV2-main\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "D:\MyProject\PYTHON\MoneyPrinterV2-main\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyProject\PYTHON\MoneyPrinterV2-main\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "D:\MyProject\PYTHON\MoneyPrinterV2-main\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Failed to set preferences: unknown error

**Comment by ElvisDream** [comment]
![1](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/26276217/797ad694-2259-4ca1-a8ae-309d99b98152)
![2](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/26276217/4489a762-7b83-42ef-9916-492b0deb835a)

**Comment by ElvisDream** [comment]
firfox version:116.0.3（64位）

**Comment by bartex100** [comment]
Did you set your Firefox profile path correctly?

**Comment by ElvisDream** [comment]
> Did you set your Firefox profile path correctly?

<img width="1330" alt="image" src="https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/26276217/34932551-5607-49c4-a73a-04b2a4d7077c">
This is how firefox addresses are configured, right?

**Comment by FujiwaraChoki** [comment]
No. Please look through the closed issues and you will find the solution.

**Comment by bartex100** [comment]
> > Did you set your Firefox profile path correctly?
> 
> <img width="1330" alt="image" src="https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/26276217/34932551-5607-49c4-a73a-04b2a4d7077c">
> This is how firefox addresses are configured, right?

Did you try to search "path to firefox profile" in Google before opening the issue?
It's %APPDATA%\Mozilla\Firefox\Profiles\your_version

**Comment by ElvisDream** [comment]
> No. Please look through the closed issues and you will find the solution.

ok  thanks

**Comment by ElvisDream** [comment]
> > > Did you set your Firefox profile path correctly?
> > 
> > 
> > <img alt="image" width="1330" src="https://private-user-images.githubusercontent.com/26276217/306899171-34932551-5607-49c4-a73a-04b2a4d7077c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTYxODgsIm5iZiI6MTcwODU5NTg4OCwicGF0aCI6Ii8yNjI3NjIxNy8zMDY4OTkxNzEtMzQ5MzI1NTEtNTYwNy00OWM0LWE3M2EtMDRiMmE0ZDcwNzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA5NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YzFjYzczNGUwZDRkZTM3MDdkYTU2NTY5MjIxMzdkYTIzOTFhMWNmYjYzMDdmYmZiNTFkNzM4OGQyYmY5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0rvI38DwuXRnK1vtWG__ixU0qKe4Q5SpXxRbqv2DMYI">
> > This is how firefox addresses are configured, right?
> 
> Did you try to search "path to firefox profile" in Google before opening the issue? It's %APPDATA%\Mozilla\Firefox\Profiles\your_version

thanks
