### ISSUE TITLE
Fail to build TTS

### ISSUE THREAD

**Issue by 23andyrt** [FujiwaraChoki/MoneyPrinterV2#34]
I'm trying to run everything, but it always gets stuck with TTS. I'm using Python v3.9.0.
> 
> _ERROR: Failed building wheel for TTS
> Failed to build TTS
> ERROR: Could not build wheels for TTS which use PEP 517 and cannot be installed directly_

And there are a bunch of red letters on top of these messages. I've tried different versions of Python, attempted to delete everything and start from scratch, and even installed it in a different folder, but none seem to work. Do you know what could be causing this?

**Comment by FujiwaraChoki** [comment]
Did you install C++ Build Tools?

**Comment by 23andyrt** [comment]
Yes man, and just to make sure I uninstall everything and reinstall it and keep saying the same error 😢. I'll try to run more test to see if I find the problem.

**Comment by FujiwaraChoki** [comment]
> Yes man, and just to make sure I uninstall everything and reinstall it and keep saying the same error 😢. I'll try to run more test to see if I find the problem. 

Run python --version

**Comment by FujiwaraChoki** [comment]
Also do pip install -U wheel

**Comment by Bluntsrl** [comment]
Did you ever find a solution?

**Comment by FujiwaraChoki** [comment]
Search on Google how to install C++ Build Tools. Also, try the solutions I mentioned.

**Comment by Bluntsrl** [comment]
Build tools are installed, I'm on python 3.9.7, also upgraded wheel
