### ISSUE TITLE
Ask for your guidance

### ISSUE THREAD

**Issue by a-Fat-boy** [FujiwaraChoki/MoneyPrinterV2#35]
I am a non-computer major graduate student, and I am very interested in your project. There is a bug in the program running according to the guidance of the file, but I do not know where the error is, I sincerely hope you can give me guidance
![Uploading bug.png…]()

**Comment by FujiwaraChoki** [comment]
Please re-upload the image, although I'm 99% sure you overlooked something kn the installation.
