### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by chongxinxiaobai** [FujiwaraChoki/MoneyPrinterV2#36]
Traceback (most recent call last):
  File "D:\Money PrinterV2\MoneyPrinterV2\src\main.py", line 14, in <module>
    from classes.YouTube import YouTube
  File "D:\Money PrinterV2\MoneyPrinterV2\src\classes\YouTube.py", line 30, in <module>
    change_settings({"IMAGEMAGICK_BINARY": get_imagemagick_path()})
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Money PrinterV2\MoneyPrinterV2\src\config.py", line 241, in get_imagemagick_path
    with open(os.path.join(ROOT_DIR, "config.json"), "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Money PrinterV2\\MoneyPrinterV2\\config.json

**Comment by InternalShadow** [comment]
you need to set the path to your magick.exe on windows
<h4>Typical Windows path</h4>
<p>  "imagemagick_path": "C:\\Program Files\\ImageMagick-7.1.0-Q16\\magick.exe"
</p>
<h4>linux/macos</h4>
 otherwise on Linux/MacOS the path to convert (usually /usr/bin/convert).

**Comment by chongxinxiaobai** [comment]
Can you give a startup config.json file download address.
