### ISSUE TITLE
Just followed the installation but getting this error message

### ISSUE THREAD

**Issue by dwk601** [FujiwaraChoki/MoneyPrinterV2#38]
Traceback (most recent call last):
  File "/home/dongwook/Project/MoneyPrinterV2/src/main.py", line 14, in <module>
    from classes.YouTube import YouTube
  File "/home/dongwook/Project/MoneyPrinterV2/src/classes/YouTube.py", line 30, in <module>
    change_settings({"IMAGEMAGICK_BINARY": get_imagemagick_path()})
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dongwook/Project/MoneyPrinterV2/src/config.py", line 241, in get_imagemagick_path
    with open(os.path.join(ROOT_DIR, "config.json"), "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/dongwook/Project/MoneyPrinterV2/config.json'

**Comment by InternalShadow** [comment]
you need to set the path to your magick.exe on windows

Typical Windows path
"imagemagick_path": "C:\\Program Files\\ImageMagick-7.1.0-Q16\\magick.exe"

linux/macos
otherwise on Linux/MacOS the path to convert (usually /usr/bin/convert).

**Comment by dwk601** [comment]
So where do I set the path to my magick.exe on windows?
I have it in: "C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe"
which file should I modify?

**Comment by bartex100** [comment]
> So where do I set the path to my magick.exe on windows? I have it in: "C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe" which file should I modify?

it is in config,json file remember to use double slashes like \\ not \
