### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by chongxinxiaobai** [FujiwaraChoki/MoneyPrinterV2#40]
Can you give a startup config.json file download address.

**Comment by heishen6** [comment]
FileNotFoundError: [Errno 2] No such file or di
<img width="736" alt="截屏2024-02-24 16 50 48" src="https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/160785663/6ee3f2bd-526b-4b7b-a264-1bc2056e32fe">
rectory: '/Users/heishen/Downloads/MoneyPrinterV2-main/venv\\Lib\\site-packages/TTS/.models.json'

**Comment by FujiwaraChoki** [comment]
What? Just follow the instructions.
