### ISSUE TITLE
Linux No such file or directory error

### ISSUE THREAD

**Issue by AMEND09** [FujiwaraChoki/MoneyPrinterV2#41]
I recently installed this on Linux, I followed all of the installation steps. I saw a similar issue for Windows but did not see a solution for Linux. Here is the more specific error:

Traceback (most recent call last):
  File "/home/adi/MoneyPrinterV2/src/main.py", line 14, in <module>
    from classes.YouTube import YouTube
  File "/home/adi/MoneyPrinterV2/src/classes/YouTube.py", line 30, in <module>
    change_settings({"IMAGEMAGICK_BINARY": get_imagemagick_path()})
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adi/MoneyPrinterV2/src/config.py", line 241, in get_imagemagick_path
    with open(os.path.join(ROOT_DIR, "config.json"), "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/adi/MoneyPrinterV2/config.json'

**Comment by FujiwaraChoki** [comment]
You did not follow the instructions, as the instructions clearly tell you to copy the config.example.json file to a file named config.json, and then fill out the variables there.
