### ISSUE TITLE
Chat error

### ISSUE THREAD

**Issue by dwoloszin** [FujiwaraChoki/MoneyPrinterV2#44]
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/10993738/d7eccf1f-efa1-43d2-8afc-adf85f1340ca)
 how do solve this error?

**Comment by FujiwaraChoki** [comment]
Try closing every firefox instance that is open/any open browser.

**Comment by dwoloszin** [comment]
that's solved the problem tk!
