### ISSUE TITLE
Too many requests [liaobots.work]

### ISSUE THREAD

**Issue by dwoloszin** [FujiwaraChoki/MoneyPrinterV2#45]
![print3](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/10993738/6ff533a9-6599-49f3-a653-306e89c10190)

bad news
https://liaobots.work/api/user
{"code":200,"msg":"success","data":"Too many requests"}

**Comment by FujiwaraChoki** [comment]
VPN

**Comment by dwoloszin** [comment]
how do I implement a VPN for the correct host?
