### ISSUE TITLE
No accounts found in cache. Create one now?

### ISSUE THREAD

**Issue by G-LJDS2022** [FujiwaraChoki/MoneyPrinterV2#48]
![1709180965305](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/134282368/7fa955f7-9210-44c0-8818-93f72da9f6ad)

**Comment by glowly112** [comment]
yes create one if you dont have

**Comment by G-LJDS2022** [comment]
What problems are there with the following setup?

{
  "verbose": true,
  "firefox_profile": "D:\Program Files\Mozilla Firefox\firefox.exe",
  "headless": false,
  "twitter_language": "Chinese",
  "llm": "gpt4",
  "image_prompt_llm": "gpt4",
  "image_model": "v3",
  "threads": 4,
  "zip_url": "",
  "is_for_kids": false,
  "google_maps_scraper": "https://github.com/gosom/google-maps-scraper/archive/refs/tags/v0.9.7.zip",
  "email": {
    "smtp_server": "smtp.gmail.com",
    "smtp_port": 587,
    "username": "",
    "password": ""
  },
  "google_maps_scraper_niche": "",
  "scraper_timeout": 300,
  "outreach_message_subject": "I have a question...",
  "outreach_message_body_file": "outreach_message.html",
  "assembly_ai_api_key": "6fee45425c1b48369c2e9",
  "font": "bold_font.ttf",
  "imagemagick_path": "D:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\magick.exe"
}

**Comment by G-LJDS2022** [comment]
> yes create one if you dont have

![1709207882453](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/134282368/ba7f4605-4b7a-4820-b009-40b46c4f7950)

**Comment by FujiwaraChoki** [comment]
This is not a tutorial on how to use the terminal, please don't open issues for things like this.
