### ISSUE TITLE
file not found error: config.json

### ISSUE THREAD

**Issue by bnorum** [FujiwaraChoki/MoneyPrinterV2#51]
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/115905633/682e41c7-dd4f-464a-9e2a-f70e9119e91b)

**Comment by bnorum** [comment]
i didnt read the instructions

**Comment by fastmirza-creator** [comment]
I have the same error do you fix this?

**Comment by Meeshkann** [comment]
since i can't read instructions too, i've encountered this problem.

Copy Example Configuration and fill out values in config.json
`cp config.example.json config.json`
