### ISSUE TITLE
how I can view the videos generated by MPV2 on my local machine? 

### ISSUE THREAD

**Issue by Elllllllvin** [FujiwaraChoki/MoneyPrinterV2#55]
Dear author:
I would like to check locally if I have successfully generated a video. How can I view it?

I run the main.py and select [Show all Shorts], and The output is as follows: 
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/100711005/106accf6-d7ee-49db-974f-3ba0cdd6b19a)

I have checked the folder in   ../AppData/Local/tts/tts_models--en--ljspeech--tacotron2-DDC_ph and all files in the folder are as follows:
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/100711005/5c0f8f6d-c802-4378-91d8-e408223901b8)

Here is my config 
``` json 
{
  "verbose": true,
  "firefox_profile": "I have filled this with my own firefox_profile",
  "headless": false,
  "twitter_language": "English",
  "llm": "gpt4",
  "image_prompt_llm": "gpt35_turbo",
  "image_model": "prodia",
  "threads": 2,
  "zip_url": "D:\\mp3sample\\mp3.zip",
  "is_for_kids": false,
  "google_maps_scraper": "https://github.com/gosom/google-maps-scraper/archive/refs/tags/v0.9.7.zip",
  "email": {
    "smtp_server": "smtp.gmail.com",
    "smtp_port": 587,
    "username": "",
    "password": ""
  },
  "google_maps_scraper_niche": "",
  "scraper_timeout": 300,
  "outreach_message_subject": "I have a question...",
  "outreach_message_body_file": "outreach_message.html",
  "assembly_ai_api_key": "I have filled this with my own assembly_ai_api_key",
  "font": "bold_font.ttf",
  "imagemagick_path": "D:\\ImageMagick-7.1.1-Q16-HDRI\\magick.exe"
}
```
How can I see the generated video locally? Hope to receive your reply, thank you

**Comment by FujiwaraChoki** [comment]
Use venv not conda and try again
