### ISSUE TITLE
RuntimeError: Incorrect response

### ISSUE THREAD

**Issue by 2679373161** [FujiwaraChoki/MoneyPrinterV2#56]
when I run the code , I get this error ,how can I fix this bug?
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/51979212/4ac745d7-884c-44c0-bb73-db637e226043)

**Comment by FujiwaraChoki** [comment]
Try using a VPN, if still doesn't work open an issue in g4f.

**Comment by 2679373161** [comment]
Thank you very much. I checked because my request was blocked by the firewall
