### ISSUE TITLE
Youtube Upload Error - Processing Abandoned

### ISSUE THREAD

**Issue by ipdeft** [FujiwaraChoki/MoneyPrinterV2#57]
Hey - Awesome project.

I've noticed some inconsistent behavior where the first time I ran the project the youtube short video uploaded without issue. However going through the workflow again results in an error from the Youtube webui during the upload step. Screenshots attached below for reference and verbose is True in the config.json
![Snag_108c54](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/68722542/2887450a-5e40-4caf-8610-6c447638a4db)
![Snag_75590](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/68722542/cbb913a0-d5a6-4da2-b369-f44cb6a7c4b4)

Do you have any suggestions on how I might best go about troubleshooting this further?

**Comment by FujiwaraChoki** [comment]
Not sure - might be helpful taking this up with YouTube Support.
