### ISSUE TITLE
Can't get it to work: No module named 'TTS'

### ISSUE THREAD

**Issue by MeridianGH** [FujiwaraChoki/MoneyPrinterV2#60]
I just can't seem to get it to work.

I installed the project cleanly by cloning from git and set up the virtual environment properly.
I am using Python 3.9.13.

Every time I try to start main.py I'm getting following error:
![grafik](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/50270402/77916ad2-3420-4c14-960c-c712227441c6)

I made sure TTS is indeed installed and tried setting up the venv again by deleting the folder and creating a new venv (both using the provided commands and by myself).

Any idea what may be causing this?

**Comment by DavidXIVII** [comment]
You are in windows & i assume you ran:
.\venv\Scripts\activate

did you ran:
pip install -r requirements.txt

Because TTS is a required 3pty Module that is being installed with much more modules

https://github.com/FujiwaraChoki/MoneyPrinterV2/blob/main/requirements.txt
