### ISSUE TITLE
TTs linux users

### ISSUE THREAD

**Issue by MrArnaudMichel** [FujiwaraChoki/MoneyPrinterV2#61]
I'm using linux (Debian 12)

By default the path of the TTs package is "venv\\Lib\\site-packages" in src/classes/Tts.py line 18.
But in my case the site-packages file was here: "venv/lib/python3.11/site-packages". After change the path, the programs works !

I don't know if it's from my machine but I don't think so.

I think it might be good to specify it in the Readme.

In any case, good job!

**Comment by FujiwaraChoki** [comment]
For people facing the same issue ^
