### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL 'in maintenance': No scheme supplied. Perhaps you meant https://in maintenance?

### ISSUE THREAD

**Issue by oBLackbeard** [FujiwaraChoki/MoneyPrinterV2#62]
how can i fix this error
![Screenshot 2024-03-10 002746](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/80417518/38be0b1e-3d91-4232-b4a4-9f421e8ceabd)

**Comment by FujiwaraChoki** [comment]
Have you changed the code in any way?

**Comment by oBLackbeard** [comment]
no

**Comment by FujiwaraChoki** [comment]
Try to google the issue, since there's nothing wrong with MP itself.
