### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/othmane/MoneyPrinterV2/venv\\Lib\\site-packages/TTS/.models.json'

### ISSUE THREAD

**Issue by oBLackbeard** [FujiwaraChoki/MoneyPrinterV2#63]
i didn't  find the descord server
![Uploading Debian 12.x 64-bit-2024-03-10-12-25-10.png…]()

**Comment by oBLackbeard** [comment]
![Debian 12 x 64-bit-2024-03-10-12-25-10](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/80417518/9842576f-eac8-4e5b-a9e4-eab63508d49c)

**Comment by FujiwaraChoki** [comment]
change the path to site packages in the code

**Comment by oBLackbeard** [comment]
Ok thanks

**Comment by Lyxc-Li** [comment]
How did you fix it in the end?
