### ISSUE TITLE
MoneyPrinterV2/transparent was not found

### ISSUE THREAD

**Issue by Bluntsrl** [FujiwaraChoki/MoneyPrinterV2#72]
![Screenshot 2024-03-27 182346](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/122750111/130024cb-fb80-4a2b-a92c-39c8956dbea2)

Receiving this after resizing the images, am I doing something wrong?

**Comment by FujiwaraChoki** [comment]
Please specify the URL to a ZIP file, as filebin has removed the original one.

**Comment by Bluntsrl** [comment]
Same error when I specify the ZIP URL

**Comment by FujiwaraChoki** [comment]
Show the output and the zip url
