### ISSUE TITLE
[Idea] Add Google Gemini support

### ISSUE THREAD

**Issue by pratham-darooka** [FujiwaraChoki/MoneyPrinterV2#75]
Hello @FujiwaraChoki, it would be amazing to have Google Gemini model support!

Similar to the one I did in https://github.com/harry0703/MoneyPrinterTurbo/pull/127

Thanks for this amazing project!

**Comment by FujiwaraChoki** [comment]
Open to PRs

**Comment by pratham-darooka** [comment]
@FujiwaraChoki can reopen this issue. Here is the PR: https://github.com/FujiwaraChoki/MoneyPrinterV2/pull/78
