### ISSUE TITLE
this happens very time i try to upload a short

### ISSUE THREAD

**Issue by gameboyssp124** [FujiwaraChoki/MoneyPrinterV2#77]
![Screenshot 2024-04-08 184126](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/122707951/06e83b0f-64c0-43d6-af85-69fab9b4017c)

i have c++ installed i don't know what I'm doing wrong

**Comment by FujiwaraChoki** [comment]
Is your Virtual Environment enabled?

**Comment by gameboyssp124** [comment]
No did I need it

**Comment by FujiwaraChoki** [comment]
If you're not even going to follow the instructions, then why create this issue??
