### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by asonsgh** [FujiwaraChoki/MoneyPrinterV2#79]
i am trying to install it within huggingface space but the problem is firefox profile path! can you please help? how can i add profile path of firefox? and how i login to firefox? i dont know how do i do this with just dockerfile. 

any solution?

**Comment by asonsgh** [comment]
is it normal for 1 minute short video? 144 images? 
![image](https://github.com/FujiwaraChoki/MoneyPrinterV2/assets/169652913/ab92bbe4-c2f3-4e2b-927a-8816dee54242)

**Comment by FujiwaraChoki** [comment]
No not really lol

**Comment by FujiwaraChoki** [comment]
When you create a new account, it will ask you for the path to your Firefox Profile Location.

**Comment by asonsgh** [comment]
> When you create a new account, it will ask you for the path to your Firefox Profile Location.

YUP you are right but the problem is Huggingface spaces are non intractive. i mean there is no terminal to intract with . we only have dockerfile or app file sooo

**Comment by FujiwaraChoki** [comment]
What does this have to do with HF spaces? If any issues were to arise, I'd assume it's because there's no graphical interface, which is why firefox cannot be used. I recommend adding the headless option and using geckodriver if things turn out to be difficult. Other than that, I'm not sure what to tell you.

**Comment by fxgurv** [comment]
ow ya you got! that's exactly what i wanted to ask !
now at this point another problem comes out.... which is i do not even know how to use "geckodriver" so can you please help a little bit? i mean can you please write a dockerfile that will cover this firefox profile?
or maybe you already have deployed it in huggingface space ? if so then i can duplicate your space.

**Comment by FujiwaraChoki** [comment]
You'll have to write one yourself, as I don't use HF spaces.

**Comment by asonsgh** [comment]
got it! thanks alot. can you recommend any platform where I can host this
bot for free like hf?
