### ISSUE TITLE
Codespace

### ISSUE THREAD

**Issue by fxgurv** [FujiwaraChoki/MoneyPrinterV2#81]
i wanted to test this in codespace could you tell me how can i make it working within codespace? i mean how can i setup headless mod? and how can i login my youtube account and get the root dir of firefox profile path in headless mode? i've never tried cli apps like this one. everything else seems to be setupd easly but at this point i am totally stuck!

**Comment by FujiwaraChoki** [comment]
Check out #79, maybe that will help

**Comment by FujiwaraChoki** [comment]
Closing as no response

**Comment by fxgurv** [comment]
I have saw and read that issue and i must say that i am still not clear. if there is something that i have to do please tell me. do i need to download gekodrivers? ok then what?

**Comment by fxgurv** [comment]
are you alive or dead?
