### ISSUE TITLE
A new chinese version MoneyPrinter released 

### ISSUE THREAD

**Issue by ddean2009** [FujiwaraChoki/MoneyPrinterV2#82]
Dear sir , I release a new chinese version MoneyPrinterPlus:

features:

Integration with large models from OpenAI, Azure, Kimi, Qianfan, Baichuan, Tongyi Qwen, DeepSeek,
Supports Azure voice capabilities
Supports Aliyun voice capabilities
Supports Tencent Cloud voice capabilities
Supports over 100 different voice types
Offers voice preview function
Offers over 30 types of video transition effects
Supports video generation in different resolutions, sizes, and aspect ratios
Supports voice selection and speaking speed adjustment
Supports background music
Supports adjustment of background music volume
Supports customized subtitles
Covers mainstream AI large model tools in the market

address : 

https://github.com/ddean2009/MoneyPrinterPlus

could you please add it to the readme ? thanks .

**Comment by FujiwaraChoki** [comment]
No sorry, we already have a chinese version.
